# Generated by Django 3.2.16 on 2022-12-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=25)),
                ('Descripcion', models.TextField(max_length=250)),
                ('Modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Valor', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Ventas', models.IntegerField()),
                ('DetalleProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.detalleproductos')),
            ],
        ),
    ]
