# Generated by Django 3.2.16 on 2022-12-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
