# Generated by Django 3.2.16 on 2022-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Ventas',
            field=models.IntegerField(default=0),
        ),
    ]
