# Generated by Django 3.2.16 on 2022-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_alter_productos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Valor',
            field=models.CharField(max_length=50),
        ),
    ]
