# Generated by Django 3.2.16 on 2022-12-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='DetalleProductos',
        ),
        migrations.DeleteModel(
            name='DetalleProductos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
